services:
  workout_db:
    image: mysql:8.0
    container_name: workout_db
    environment:
      MYSQL_ROOT_PASSWORD: workout
      MYSQL_DATABASE: workout
      MYSQL_USER: workout
      MYSQL_PASSWORD: workout
    ports:
      - "4406:3306"
    volumes:
      - workout_db_data:/var/lib/mysql

  workout_backend:
    image: marijndemul16/workout.backend:latest
    container_name: workout_backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=workout_db;Database=workout;User=workout;Password=workout;
    ports:
      - "7087:7087"
    depends_on:
      - workout_db

  workout_frontend:
    image: marijndemul16/workout.frontend:latest
    container_name: workout_frontend
    ports:
      - "3500:5173"
    depends_on:
      - workout_backend

  workout_watchtower:
    image: containrrr/watchtower
    container_name: workout_watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300

volumes:
  workout_db_data: