services:
  workout_db:
    image: mysql:8.0
    container_name: workout_db
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: workout
      MYSQL_DATABASE: workout
      MYSQL_USER: workout
      MYSQL_PASSWORD: workout
    ports:
      - "3502:3306"
    volumes:
      - workout_db_data:/var/lib/mysql

  workout_backend:
    image: marijndemul16/workout.backend:latest
    container_name: workout_backend
    platform: linux/amd64
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=workout_db;Database=workout;User=workout;Password=workout;
    ports:
      - "3501:8080"
    depends_on:
      - workout_db

  workout_frontend:
    image: marijndemul16/workout.frontend:latest
    container_name: workout_frontend
    platform: linux/amd64
    ports:
      - "3500:3000"
    depends_on:
      - workout_backend

  workout_watchtower:
    image: containrrr/watchtower
    container_name: workout_watchtower
    platform: linux/amd64
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300

volumes:
  workout_db_data: