version: '3.8'

services:
  backend:
    image: marijndemul16/workout.backend:latest
    ports:
      - "5000:5000"
    networks:
      - workout-backend-network
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: workout
      MYSQL_USER: workout
      MYSQL_PASSWORD: workout
    ports:
      - "3502:3306"
    networks:
      - workout-backend-network
    volumes:
      - workout_db_data:/var/lib/mysql

networks:
  workout-backend-network:
    driver: bridge

volumes:
  workout_db_data: